/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Atualizar Objeto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.daogen2.AtualizarObjeto#getAtr <em>Atr</em>}</li>
 * </ul>
 *
 * @see org.xtext.daogen2.Daogen2Package#getAtualizarObjeto()
 * @model
 * @generated
 */
public interface AtualizarObjeto extends Parametro
{
  /**
   * Returns the value of the '<em><b>Atr</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Atr</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Atr</em>' reference.
   * @see #setAtr(Atributo)
   * @see org.xtext.daogen2.Daogen2Package#getAtualizarObjeto_Atr()
   * @model
   * @generated
   */
  Atributo getAtr();

  /**
   * Sets the value of the '{@link org.xtext.daogen2.AtualizarObjeto#getAtr <em>Atr</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Atr</em>' reference.
   * @see #getAtr()
   * @generated
   */
  void setAtr(Atributo value);

} // AtualizarObjeto
