/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Classe</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.daogen2.Classe#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link org.xtext.daogen2.Classe#getFeatures <em>Features</em>}</li>
 * </ul>
 *
 * @see org.xtext.daogen2.Daogen2Package#getClasse()
 * @model
 * @generated
 */
public interface Classe extends Type
{
  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Super Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(Classe)
   * @see org.xtext.daogen2.Daogen2Package#getClasse_SuperType()
   * @model
   * @generated
   */
  Classe getSuperType();

  /**
   * Sets the value of the '{@link org.xtext.daogen2.Classe#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(Classe value);

  /**
   * Returns the value of the '<em><b>Features</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.daogen2.Feature}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Features</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Features</em>' containment reference list.
   * @see org.xtext.daogen2.Daogen2Package#getClasse_Features()
   * @model containment="true"
   * @generated
   */
  EList<Feature> getFeatures();

} // Classe
