/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.daogen2.Daogen2Package
 * @generated
 */
public interface Daogen2Factory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  Daogen2Factory eINSTANCE = org.xtext.daogen2.impl.Daogen2FactoryImpl.init();

  /**
   * Returns a new object of class '<em>Daogen</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Daogen</em>'.
   * @generated
   */
  Daogen createDaogen();

  /**
   * Returns a new object of class '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Type</em>'.
   * @generated
   */
  Type createType();

  /**
   * Returns a new object of class '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Data Type</em>'.
   * @generated
   */
  DataType createDataType();

  /**
   * Returns a new object of class '<em>Classe</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Classe</em>'.
   * @generated
   */
  Classe createClasse();

  /**
   * Returns a new object of class '<em>Feature</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Feature</em>'.
   * @generated
   */
  Feature createFeature();

  /**
   * Returns a new object of class '<em>Atributo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atributo</em>'.
   * @generated
   */
  Atributo createAtributo();

  /**
   * Returns a new object of class '<em>Insert Code</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Insert Code</em>'.
   * @generated
   */
  InsertCode createInsertCode();

  /**
   * Returns a new object of class '<em>Parametro</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Parametro</em>'.
   * @generated
   */
  Parametro createParametro();

  /**
   * Returns a new object of class '<em>Inserir Objeto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Inserir Objeto</em>'.
   * @generated
   */
  InserirObjeto createInserirObjeto();

  /**
   * Returns a new object of class '<em>Buscar Objeto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Buscar Objeto</em>'.
   * @generated
   */
  BuscarObjeto createBuscarObjeto();

  /**
   * Returns a new object of class '<em>Listar Objeto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Listar Objeto</em>'.
   * @generated
   */
  ListarObjeto createListarObjeto();

  /**
   * Returns a new object of class '<em>Remover Objeto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Remover Objeto</em>'.
   * @generated
   */
  RemoverObjeto createRemoverObjeto();

  /**
   * Returns a new object of class '<em>Atualizar Objeto</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Atualizar Objeto</em>'.
   * @generated
   */
  AtualizarObjeto createAtualizarObjeto();

  /**
   * Returns a new object of class '<em>Deletar Tabela</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Deletar Tabela</em>'.
   * @generated
   */
  DeletarTabela createDeletarTabela();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  Daogen2Package getDaogen2Package();

} //Daogen2Factory
