/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Deletar Tabela</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.daogen2.Daogen2Package#getDeletarTabela()
 * @model
 * @generated
 */
public interface DeletarTabela extends Parametro
{
} // DeletarTabela
