/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Feature</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.daogen2.Daogen2Package#getFeature()
 * @model
 * @generated
 */
public interface Feature extends EObject
{
} // Feature
