/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Insert Code</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.daogen2.InsertCode#getParametro <em>Parametro</em>}</li>
 * </ul>
 *
 * @see org.xtext.daogen2.Daogen2Package#getInsertCode()
 * @model
 * @generated
 */
public interface InsertCode extends Feature
{
  /**
   * Returns the value of the '<em><b>Parametro</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Parametro</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parametro</em>' containment reference.
   * @see #setParametro(Parametro)
   * @see org.xtext.daogen2.Daogen2Package#getInsertCode_Parametro()
   * @model containment="true"
   * @generated
   */
  Parametro getParametro();

  /**
   * Sets the value of the '{@link org.xtext.daogen2.InsertCode#getParametro <em>Parametro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Parametro</em>' containment reference.
   * @see #getParametro()
   * @generated
   */
  void setParametro(Parametro value);

} // InsertCode
