/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parametro</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.daogen2.Daogen2Package#getParametro()
 * @model
 * @generated
 */
public interface Parametro extends EObject
{
} // Parametro
