/*
 * generated by Xtext 2.15.0
 */
package org.xtext.validation

import org.eclipse.xtext.validation.Check
import org.xtext.daogen2.Classe
import org.xtext.daogen2.Atributo
import org.xtext.daogen2.Daogen2Package

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class Daogen2Validator extends AbstractDaogen2Validator {
	
	@Check
	def void checkNomeComecaComMaiusculo(Classe classe) {
    	if (!Character.isUpperCase(classe.name.charAt(0))) {
        	warning("O nome da classe deve começar com letra maiúscula", 
            	Daogen2Package.Literals.TYPE__NAME)
    	}
	}
	
	@Check
	def void checkNomeTem16CharMax(Classe classe) {
    	if (classe.name.length > 16) {
        	warning("O nome da classe deve ter no máximo 16 caracteres", 
            	Daogen2Package.Literals.TYPE__NAME)
    	}
	}
	
	@Check
	def void checkAtributoComecaComMinusculo(Atributo atributo) {
    	if (!Character.isLowerCase(atributo.name.charAt(0))) {
        	warning("O nome do atributo deve começar com letra minúscula", 
            	Daogen2Package.Literals.TYPE__NAME)
    	}
	}
	
}