/*
 * generated by Xtext 2.15.0
 */
package org.xtext.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.Daogen2RuntimeModule
import org.xtext.Daogen2StandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class Daogen2IdeSetup extends Daogen2StandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new Daogen2RuntimeModule, new Daogen2IdeModule))
	}
	
}
