/**
 * generated by Xtext 2.15.0
 */
package org.xtext.ui.contentassist;

import org.xtext.ui.contentassist.AbstractDaogen2ProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class Daogen2ProposalProvider extends AbstractDaogen2ProposalProvider {
}
