/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.daogen2.Atributo;
import org.xtext.daogen2.AtualizarObjeto;
import org.xtext.daogen2.Daogen2Package;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Atualizar Objeto</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.daogen2.impl.AtualizarObjetoImpl#getAtr <em>Atr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AtualizarObjetoImpl extends ParametroImpl implements AtualizarObjeto
{
  /**
   * The cached value of the '{@link #getAtr() <em>Atr</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAtr()
   * @generated
   * @ordered
   */
  protected Atributo atr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AtualizarObjetoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Daogen2Package.Literals.ATUALIZAR_OBJETO;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Atributo getAtr()
  {
    if (atr != null && atr.eIsProxy())
    {
      InternalEObject oldAtr = (InternalEObject)atr;
      atr = (Atributo)eResolveProxy(oldAtr);
      if (atr != oldAtr)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, Daogen2Package.ATUALIZAR_OBJETO__ATR, oldAtr, atr));
      }
    }
    return atr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Atributo basicGetAtr()
  {
    return atr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setAtr(Atributo newAtr)
  {
    Atributo oldAtr = atr;
    atr = newAtr;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Daogen2Package.ATUALIZAR_OBJETO__ATR, oldAtr, atr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Daogen2Package.ATUALIZAR_OBJETO__ATR:
        if (resolve) return getAtr();
        return basicGetAtr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Daogen2Package.ATUALIZAR_OBJETO__ATR:
        setAtr((Atributo)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Daogen2Package.ATUALIZAR_OBJETO__ATR:
        setAtr((Atributo)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Daogen2Package.ATUALIZAR_OBJETO__ATR:
        return atr != null;
    }
    return super.eIsSet(featureID);
  }

} //AtualizarObjetoImpl
