/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.daogen2.Daogen2Package;
import org.xtext.daogen2.DeletarTabela;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Deletar Tabela</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class DeletarTabelaImpl extends ParametroImpl implements DeletarTabela
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected DeletarTabelaImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Daogen2Package.Literals.DELETAR_TABELA;
  }

} //DeletarTabelaImpl
