/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.daogen2.Daogen2Package;
import org.xtext.daogen2.InserirObjeto;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Inserir Objeto</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class InserirObjetoImpl extends ParametroImpl implements InserirObjeto
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InserirObjetoImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Daogen2Package.Literals.INSERIR_OBJETO;
  }

} //InserirObjetoImpl
