/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.daogen2.Daogen2Package;
import org.xtext.daogen2.InsertCode;
import org.xtext.daogen2.Parametro;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Insert Code</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.daogen2.impl.InsertCodeImpl#getParametro <em>Parametro</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InsertCodeImpl extends FeatureImpl implements InsertCode
{
  /**
   * The cached value of the '{@link #getParametro() <em>Parametro</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParametro()
   * @generated
   * @ordered
   */
  protected Parametro parametro;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InsertCodeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Daogen2Package.Literals.INSERT_CODE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Parametro getParametro()
  {
    return parametro;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParametro(Parametro newParametro, NotificationChain msgs)
  {
    Parametro oldParametro = parametro;
    parametro = newParametro;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Daogen2Package.INSERT_CODE__PARAMETRO, oldParametro, newParametro);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setParametro(Parametro newParametro)
  {
    if (newParametro != parametro)
    {
      NotificationChain msgs = null;
      if (parametro != null)
        msgs = ((InternalEObject)parametro).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Daogen2Package.INSERT_CODE__PARAMETRO, null, msgs);
      if (newParametro != null)
        msgs = ((InternalEObject)newParametro).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Daogen2Package.INSERT_CODE__PARAMETRO, null, msgs);
      msgs = basicSetParametro(newParametro, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Daogen2Package.INSERT_CODE__PARAMETRO, newParametro, newParametro));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Daogen2Package.INSERT_CODE__PARAMETRO:
        return basicSetParametro(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Daogen2Package.INSERT_CODE__PARAMETRO:
        return getParametro();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Daogen2Package.INSERT_CODE__PARAMETRO:
        setParametro((Parametro)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Daogen2Package.INSERT_CODE__PARAMETRO:
        setParametro((Parametro)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Daogen2Package.INSERT_CODE__PARAMETRO:
        return parametro != null;
    }
    return super.eIsSet(featureID);
  }

} //InsertCodeImpl
