/**
 * generated by Xtext 2.15.0
 */
package org.xtext.scoping;

import org.xtext.scoping.AbstractDaogen2ScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class Daogen2ScopeProvider extends AbstractDaogen2ScopeProvider {
}
