/**
 * generated by Xtext 2.15.0
 */
package org.xtext.daogen2.util;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

import org.xtext.daogen2.*;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see org.xtext.daogen2.Daogen2Package
 * @generated
 */
public class Daogen2Switch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static Daogen2Package modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Daogen2Switch()
  {
    if (modelPackage == null)
    {
      modelPackage = Daogen2Package.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case Daogen2Package.DAOGEN:
      {
        Daogen daogen = (Daogen)theEObject;
        T result = caseDaogen(daogen);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.TYPE:
      {
        Type type = (Type)theEObject;
        T result = caseType(type);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.DATA_TYPE:
      {
        DataType dataType = (DataType)theEObject;
        T result = caseDataType(dataType);
        if (result == null) result = caseType(dataType);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.CLASSE:
      {
        Classe classe = (Classe)theEObject;
        T result = caseClasse(classe);
        if (result == null) result = caseType(classe);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.FEATURE:
      {
        Feature feature = (Feature)theEObject;
        T result = caseFeature(feature);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.ATRIBUTO:
      {
        Atributo atributo = (Atributo)theEObject;
        T result = caseAtributo(atributo);
        if (result == null) result = caseFeature(atributo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.INSERT_CODE:
      {
        InsertCode insertCode = (InsertCode)theEObject;
        T result = caseInsertCode(insertCode);
        if (result == null) result = caseFeature(insertCode);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.PARAMETRO:
      {
        Parametro parametro = (Parametro)theEObject;
        T result = caseParametro(parametro);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.INSERIR_OBJETO:
      {
        InserirObjeto inserirObjeto = (InserirObjeto)theEObject;
        T result = caseInserirObjeto(inserirObjeto);
        if (result == null) result = caseParametro(inserirObjeto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.BUSCAR_OBJETO:
      {
        BuscarObjeto buscarObjeto = (BuscarObjeto)theEObject;
        T result = caseBuscarObjeto(buscarObjeto);
        if (result == null) result = caseParametro(buscarObjeto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.LISTAR_OBJETO:
      {
        ListarObjeto listarObjeto = (ListarObjeto)theEObject;
        T result = caseListarObjeto(listarObjeto);
        if (result == null) result = caseParametro(listarObjeto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.REMOVER_OBJETO:
      {
        RemoverObjeto removerObjeto = (RemoverObjeto)theEObject;
        T result = caseRemoverObjeto(removerObjeto);
        if (result == null) result = caseParametro(removerObjeto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.ATUALIZAR_OBJETO:
      {
        AtualizarObjeto atualizarObjeto = (AtualizarObjeto)theEObject;
        T result = caseAtualizarObjeto(atualizarObjeto);
        if (result == null) result = caseParametro(atualizarObjeto);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case Daogen2Package.DELETAR_TABELA:
      {
        DeletarTabela deletarTabela = (DeletarTabela)theEObject;
        T result = caseDeletarTabela(deletarTabela);
        if (result == null) result = caseParametro(deletarTabela);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Daogen</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Daogen</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDaogen(Daogen object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Type</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Type</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseType(Type object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Data Type</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Data Type</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDataType(DataType object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Classe</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Classe</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseClasse(Classe object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Feature</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Feature</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseFeature(Feature object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Atributo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Atributo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAtributo(Atributo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Insert Code</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Insert Code</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInsertCode(InsertCode object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Parametro</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Parametro</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseParametro(Parametro object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Inserir Objeto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Inserir Objeto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseInserirObjeto(InserirObjeto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Buscar Objeto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Buscar Objeto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseBuscarObjeto(BuscarObjeto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Listar Objeto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Listar Objeto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseListarObjeto(ListarObjeto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Remover Objeto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Remover Objeto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseRemoverObjeto(RemoverObjeto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Atualizar Objeto</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Atualizar Objeto</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseAtualizarObjeto(AtualizarObjeto object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>Deletar Tabela</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>Deletar Tabela</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseDeletarTabela(DeletarTabela object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //Daogen2Switch
