/*
 * generated by Xtext 2.15.0
 */
package org.xtext


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class Daogen2StandaloneSetup extends Daogen2StandaloneSetupGenerated {

	def static void doSetup() {
		new Daogen2StandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
