/**
 * generated by Xtext 2.15.0
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.ui.AbstractDaogen2UiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class Daogen2UiModule extends AbstractDaogen2UiModule {
  public Daogen2UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
