/**
 * generated by Xtext 2.15.0
 */
package org.xtext.ide;

import org.xtext.ide.AbstractDaogen2IdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class Daogen2IdeModule extends AbstractDaogen2IdeModule {
}
