/*
 * generated by Xtext 2.15.0
 */
package org.xtext.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.daogen2.ui.internal.Daogen2Activator;

public class Daogen2UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return Daogen2Activator.getInstance().getInjector("org.xtext.Daogen2");
	}

}
