/**
 * generated by Xtext 2.15.0
 */
package org.xtext;

import org.xtext.Daogen2StandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class Daogen2StandaloneSetup extends Daogen2StandaloneSetupGenerated {
  public static void doSetup() {
    new Daogen2StandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
